### request
GET https://127.0.0.1:9999/request/limit?name=tyf&age=18
content-type: application/json
myHeader: big

###
GET https://127.0.0.1:9999/request/servlet

###
GET https://127.0.0.1:9999/request/param?id=1&name=tyf&time=Mon Oct 29 17:16:04 CST 2018

###
GET https://127.0.0.1:9999/request/paramObject?id=1&name=tyf&age=25&time=Mon Oct 29 17:16:04 CST 2018

###
GET https://127.0.0.1:9999/request/url/p1/p2

###
GET https://127.0.0.1:9999/request/urlMap/p1/p2

###
GET https://127.0.0.1:9999/request/header
content-type: application/json
X-Custom-Header: Mon Oct 29 17:16:04 CST 2018

###
POST https://127.0.0.1:9999/request/form
content-type: application/x-www-form-urlencoded

id=1
&name=tyf
&age=25
&gender=BOY
&enabled=true
&time=Mon Oct 29 17:16:04 CST 2018

###
POST https://127.0.0.1:9999/request/json
content-type: application/json

{
    "id":"2",
    "name":"tyf",
    "age":25,
    "enabled":true,
    "gender":"BOY",
    "time":"2020-11-24 12:00:00"
}

###
POST https://127.0.0.1:9999/request/entity
content-type: application/json

{
    "id":"2",
    "name":"tyf",
    "age":25,
    "enabled":true,
    "gender":"BOY",
    "time":"2020-11-24 12:00:00"
}

### response
GET https://127.0.0.1:9999/response/

###
GET https://127.0.0.1:9999/response/board

###
GET https://127.0.0.1:9999/response/user1/1

###
GET https://127.0.0.1:9999/response/user2/2

### valid
POST https://127.0.0.1:9999/valid/validDto
content-type: application/json

{
    "id":"1",
    "name":"tyf",
    "age":25,
    "enabled":true,
    "gender":"BOY",
    "time":"2020-11-24 12:00:00"
}

###
POST https://127.0.0.1:9999/valid/validParam
content-type: application/x-www-form-urlencoded

id=1
&name=tyf

###
POST https://127.0.0.1:9999/valid/validAuth

### download
GET https://127.0.0.1:9999/file/download

### Security
GET https://127.0.0.1:9999/security/token
Authorization: Basic YWRtaW46MTIzNDU2

###
GET https://127.0.0.1:9999/security/hello
Authorization: bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NzY5ODk4NzksImlhdCI6MTY3Njk1Mzg3OSwic2NvcGUiOiJhcHAifQ.cXBwaOcOuidUXFRgKgAg2g0IkJeU8df3UpV7V8QgtpVgW6cTKzEwaLkzc7_VF8_41C9kq8t3FikQ50Df3_A5EdMvFG5AkfBusli8vUQziBPfLaIBmsNZpUqViWkiZubZER9p3hJDAg2tq4hdKUx4a4XmC-NPe5recnM-M0MfJ8k3rtrVCTwbPSgZuGDl3Hmv6eCz46N77IYRHKrVyJieVZZyI6Ye3vsyaiSGSvgAzzF8wJQRLoWZSiPKSuE6QBaHPys71YKEtZwWLYH1SsNA8MMOx8Ia3cFGm4eGFQsn4tja4jXc6vaXW4v0chhyu_EYNepUJp8L67p5fyd8a0DfsA
Content-Type: application/x-www-form-urlencoded

###