# 数据源配置
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dev;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  sql:
    init:
      mode:
      platform: h2
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop